name: starlane_client
description: Starlane Global Client App - Luxury Services Platform
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5

  # Networking & API
  dio: ^5.3.2
  retrofit: ^4.0.3
  json_annotation: ^4.8.1

  # UI & Design System
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  smooth_page_indicator: ^1.1.0
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0

  # Navigation
  go_router: ^12.1.1

  # Storage & Security
  flutter_secure_storage: ^9.0.0

  # JWT & Authentication
  jwt_decoder: ^2.0.1

  # Utilities & Permissions
  intl: ^0.19.0
  permission_handler: ^11.0.1
  image_picker: ^1.0.4
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^3.0.0

  # Code Generation
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
